const palette = {
  black: '#101010',
  nearBlack: '#171716',
  charcoal: '#21211F',
  graphite: '#30302D',
  slate: '#4D4A45',
  steel: '#817B72',
  fog: '#DED8CE',
  paper: '#F7F3EC',
  linen: '#FCFAF6',
  cream: '#EFE8DD',
  white: '#FFFFFF',

  accent: '#F05A24',
  accentMuted: '#FF8B5F',
  accentSoft: '#FFE1D2',

  mint: '#CDEBDD',
  success: '#1F9D59',
  warning: '#B7791F',
  danger: '#D9483F',
};

export const lightColors = {
  background: palette.paper,
  surface: palette.linen,
  surfaceElevated: palette.white,
  surfaceMuted: palette.cream,
  surfacePressed: '#F0E7DA',
  border: palette.fog,
  borderStrong: '#CFC5B7',
  textPrimary: palette.black,
  textSecondary: palette.slate,
  textMuted: palette.steel,
  textInverse: palette.white,
  accent: palette.accent,
  accentMuted: palette.accentMuted,
  accentSoft: palette.accentSoft,
  success: palette.success,
  successSoft: palette.mint,
  warning: palette.warning,
  warningSoft: '#F9E4B7',
  danger: palette.danger,
  dangerSoft: '#F8D5D1',
  shadow: '#2C241A',
  overlay: 'rgba(16, 16, 16, 0.32)',
};

export const darkColors = {
  background: palette.black,
  surface: palette.nearBlack,
  surfaceElevated: palette.charcoal,
  surfaceMuted: palette.graphite,
  surfacePressed: '#2A2A27',
  border: palette.graphite,
  borderStrong: '#42423E',
  textPrimary: palette.white,
  textSecondary: '#D9D2C8',
  textMuted: palette.steel,
  textInverse: palette.black,
  accent: palette.accent,
  accentMuted: palette.accentMuted,
  accentSoft: 'rgba(240, 90, 36, 0.2)',
  success: palette.success,
  successSoft: 'rgba(31, 157, 89, 0.18)',
  warning: palette.warning,
  warningSoft: 'rgba(183, 121, 31, 0.18)',
  danger: palette.danger,
  dangerSoft: 'rgba(217, 72, 63, 0.18)',
  shadow: '#000000',
  overlay: 'rgba(0, 0, 0, 0.5)',
};

export type ThemeColors = typeof lightColors;
